task: tkinter_frontend
main_window:
  title: "Tkinter Frontend"
  object_type: tk.Tk # App
  size:
    width: 400
    height: 400
  theme:
    default: dark
    light:
      background_color: "#EEEEEE"
      foreground_color: "#000000"
    dark:
      background_color: "#000000"
      foreground_color: "#EEEEEE"
  color_scheme: "dark"  # Use dark theme (can be 'light' or 'dark')
  fonts:
    body_font: Arial 12
    header_font: Arial 16 bold

